/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.alidron.ssh;

/**
 *
 * @author lexa
 */
public class PasswordAskerForm extends javax.swing.JPanel {

    /**
     * Creates new form PasswordAskerForm
     */
    public PasswordAskerForm() {
        initComponents();
    }
    
    public char[]getInputPassword() {
        return jPF_password.getPassword();
    }
    
    public boolean shouldSavePassword() {
        return jCB_save.getSelectedObjects() != null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_password = new javax.swing.JLabel();
        jPF_password = new javax.swing.JPasswordField();
        jCB_save = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jL_password, org.openide.util.NbBundle.getMessage(PasswordAskerForm.class, "PasswordAskerForm.jL_password.text")); // NOI18N

        jPF_password.setText(org.openide.util.NbBundle.getMessage(PasswordAskerForm.class, "PasswordAskerForm.jPF_password.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCB_save, org.openide.util.NbBundle.getMessage(PasswordAskerForm.class, "PasswordAskerForm.jCB_save.text")); // NOI18N
        jCB_save.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCB_save)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPF_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_password)
                    .addComponent(jPF_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCB_save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCB_save;
    private javax.swing.JLabel jL_password;
    private javax.swing.JPasswordField jPF_password;
    // End of variables declaration//GEN-END:variables
}
